
mybatis:
  type-aliases-package: com.test.model
  mapper-locations: classpath:com/test/dao/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_dplink_db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "123456"
    dbcp2:
      max-idle: 30
      max-total: 300
      initial-size: 10
      min-idle: 5

  # 整合redis 集群
  redis:
    #cluster:
      #nodes: 192.168.1.30:7000,192.168.1.30:7001,192.168.1.30:7002
    # 整合redis 单机
    host: 127.0.0.1
    port: 6379